# mdformat configuration | https://mdformat.readthedocs.io
[mdformat]
wrap = 88
number = false
end_of_line = "lf"

[mdformat.options]
# GitHub Flavored Markdown
gfm = true
# Preserve trailing spaces
preserve_trailing_spaces = false
