[defaults]
ignore="dirty"
update="rebase"
branch="main"

[auto-boost-essential]
path        ="vendor/auto-boost-essential"
url         ="https://github.com/nekotrix/auto-boost-algorithm.git"
sparse_paths=["Auto-Boost-Essential.py"]
shallow     =true
active      =false
