hide-mouse-cursor-when-typing = false
confirm-before-quit = false

[bell]
visual = false
audio = false

[cursor]
blinking = false

[editor]
program = "micro"
args = []
env-vars = ["COLORTERM=truecolor"]

[window]
opacity = 1.0
blur = false
decorations = "enabled"
mode = "Windowed"

[renderer]
performance = "High"
backend = "Automatic"
disable-unfocused-render = false
disable-occluded-render = true
target-fps = 60

[keyboard]
use-kitty-keyboard-protocol = true
ime-cursor-positioning = true

[fonts]
family = "JetBrainsMono Nerd Font Mono"
size = 13
features = ["zero", "calt", "liga", "ss01", "ss02", "ss19", "ss20"]
hinting = true

[fonts.regular]
family = "JetBrainsMono Nerd Font Mono"
weight = 400

[fonts.bold]
family = "JetBrainsMono Nerd Font Mono"
weight = 800

[fonts.emoji]
family = "Noto Color Emoji"

[scroll]
multiplier = 2.5

[navigation]
mode = "bookmark"
clickable = true
hide-if-single = true

[developer]
log-level = "OFF"

[shell]
program = "/usr/bin/fish"
args = ["--login"]
