# https://bun.sh/docs/runtime/bunfig
telemetry = false
smol = false
logLevel = "error"
trimWildcards = true

[install]
auto = "auto"
production = true
optional = false
peer = false
dev = false
exact = false
frozenLockfile = false
linker = "hoisted"
cacheHardLinks = true
preferOffline = true
preferLatest = true
concurrency = 16

[run]
silent = true
bun = true
hot = false

[test]
coverageSkipTestFiles = true
bail = true
timeout = 5000
preload = []
coverage = false
smol = true

[install.scopes]
"@jsr" = "https://npm.jsr.io"

# Enable loader for TypeScript settings files
# This allows us to use .bunfig.ts for configuration with onCreate callbacks
[loader]
".ts" = "bun"
