enable_selector = false
# TODO: switch to kde optimal
#selector = "rofi -dmenu -i -p 'Open With: '"
term_exec_args = '-e'
expand_wildcards = true

# TODO: enhance with https://github.com/Anomalocaridid/handlr-regex
