enable_selector = true
# Wayland selector (wofi)
selector = "wofi --dmenu -i -p 'Open With: '"
term_exec_args = '-e'
expand_wildcards = true

# TODO: enhance with https://github.com/Anomalocaridid/handlr-regex
