name: imgcmp
on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * 1" # Weekly build
permissions:
  contents: write
  pull-requests: write
jobs:
  imgcmp:
    uses: Ven0m0/.github/.github/workflows/imgcmp.yml@main
    secrets: inherit
